#!/usr/bin/env python3
"""Write `src/licenses/third_party.rs`: the license notice of every crate
SetListArray is built from, for the Licenses screen to show.

MIT, BSD and Apache all ask the same thing of anyone who ships a binary built
from them: that the copyright notice and the license text go with it. An APK is
such a binary, built from a few hundred crates. cargo-about does the gathering
— it reads each crate's *own* license files, which is where the copyright lines
that make one MIT notice different from the next actually live — and this
script does the rest:

* It checks that every crate a build for each target in `about.toml` actually
  compiles came back with a notice. cargo-about leaves out a crate with no
  `license` key without a word, which is exactly how `rinch-android` — shipped
  in every APK — went missing on the first run. "Actually compiles" is
  `cargo tree`'s answer, not `cargo metadata`'s: the latter's resolve graph
  also lists optional dependencies that are only named through a weak feature
  (`dep?/std`) and never built, and on 2026-09-10 that put `borsh`, `glifo`,
  `termcolor` and a second `vello_common` in a graph they are not in.
* The Android targets are resolved with `rinch/android-gpu`, because that is
  what `build-apk.sh` builds by default (and what
  `the_phone_gets_the_gpu_painter_by_default` holds it to); cargo-about is run
  with it too, so its graph is a superset of every build this app has.
* It leaves SetListArray itself out. The app's own license is the first thing
  the screen shows, not one third-party notice among many.
* It groups crates by the text they ship, ignoring whitespace, so dozens of
  copies of the Apache license that differ only in how they were wrapped
  become one row.
* It writes Rust rather than a text asset, so the app shows the notices with
  no parsing at runtime, and `glyph_coverage` checks every character of them
  against the bundled fonts like any other string the app draws.

It also records the `Cargo.lock` it was generated against, and
`licenses::tests::the_notices_were_generated_from_this_cargo_lock` compares
that record with the real file: a dependency added or bumped without re-running
this fails a test on a laptop instead of shipping unattributed.

    python3 scripts/make-notices.py

Needs cargo-about with its CLI feature, which is not on by default:
`cargo install cargo-about --features cli --locked`.
"""

import json
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "licenses" / "third_party.rs"
SELF = "setlistarray"
ANDROID_FEATURES = "rinch/android-gpu"

HEADER = """\
// @generated by scripts/make-notices.py from cargo-about and Cargo.lock.
// Do not edit by hand. Re-run the script after anything that changes
// Cargo.lock; `licenses::tests::the_notices_were_generated_from_this_cargo_lock`
// fails until it is.
"""


def run(*args: str) -> str:
    done = subprocess.run(args, cwd=ROOT, capture_output=True, text=True)
    if done.returncode != 0:
        sys.stderr.write(done.stderr)
        sys.exit(f"`{' '.join(args)}` failed")
    return done.stdout


def build_graph(target: str) -> set[tuple[str, str]]:
    """Every package a build for `target` compiles — normal and build
    dependencies, dev-dependencies left out — as cargo's own feature resolver
    decides it."""
    features = ["--features", ANDROID_FEATURES] if "android" in target else []
    tree = run(
        "cargo", "tree", "--target", target, "-e", "normal,build",
        "--prefix", "none", "--no-dedupe", *features,
    )
    graph = set()
    for line in tree.splitlines():
        name, _, rest = line.partition(" v")
        if rest:
            graph.add((name, rest.split(" ")[0]))
    return graph


def locked_packages() -> list[str]:
    lock = tomllib.loads((ROOT / "Cargo.lock").read_text())
    return sorted(f'{p["name"]} {p["version"]}' for p in lock["package"])


def clean(text: str) -> str:
    """CRLF to LF, trailing spaces off every line, blank lines off both ends."""
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    return "\n".join(line.rstrip() for line in lines).strip("\n")


def rust_string(s: str) -> str:
    """A Rust string literal with every control character escaped.

    Newlines especially. Rust would take a raw line break inside a literal,
    and the first version of this script wrote them that way — then
    `glyph_coverage` flagged 8,673 of them, because a raw U+000A in a literal
    is a character with no glyph, and that test is right not to guess which
    literals will be laid out with line breaks collapsed. As the two-character
    `\\n` escape it is plain ASCII to that scan, the same as every other
    `\\n` in the crate."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) >= 32:
            out.append(ch)
        else:
            out.append(f"\\u{{{ord(ch):x}}}")
    return '"' + "".join(out) + '"'


def rust_text(text: str) -> str:
    """A long text as `concat!` of one literal per line, so the generated file
    reads as the license does rather than as one line per license."""
    lines = text.split("\n")
    parts = [rust_string(line + "\n") for line in lines[:-1]] + [rust_string(lines[-1])]
    return "concat!(\n" + "".join(f"            {part},\n" for part in parts) + "        )"


def main() -> None:
    about = json.loads(
        run("cargo", "about", "generate", "--format", "json", "--features", ANDROID_FEATURES)
    )
    targets = tomllib.loads((ROOT / "about.toml").read_text())["targets"]

    groups: dict[str, dict] = {}
    attributed: set[tuple[str, str]] = set()
    for lic in about["licenses"]:
        text = clean(lic["text"])
        for use in lic["used_by"]:
            crate = use["crate"]
            attributed.add((crate["name"], crate["version"]))
            if crate["name"] == SELF:
                continue
            group = groups.setdefault(
                " ".join(text.split()),
                {"license": lic["name"], "spdx": lic["id"], "text": text, "crates": set()},
            )
            group["crates"].add(f'{crate["name"]} {crate["version"]}')

    for target in targets:
        missing = sorted(build_graph(target) - attributed)
        if missing:
            sys.exit(
                f"{target}: no notice for "
                + ", ".join(f"{name} {version}" for name, version in missing)
                + "\nMost likely a crate with no `license` key in its Cargo.toml,"
                " which cargo-about leaves out without a word."
            )

    notices = sorted(groups.values(), key=lambda g: (g["license"], min(g["crates"])))
    lines = [HEADER, "use super::Notice;", "", "pub static NOTICES: &[Notice] = &["]
    for g in notices:
        lines += [
            "    Notice {",
            f"        license: {rust_string(g['license'])},",
            f"        spdx: {rust_string(g['spdx'])},",
            "        crates: &[" + ", ".join(rust_string(c) for c in sorted(g["crates"])) + "],",
            f"        text: {rust_text(g['text'])},",
            "    },",
        ]
    lines += [
        "];",
        "",
        "/// Every package in `Cargo.lock` when this file was written, as `name version`.",
        "pub static GENERATED_FROM: &[&str] = &[",
    ]
    lines += [f"    {rust_string(p)}," for p in locked_packages()]
    lines.append("];")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    crates = sum(len(g["crates"]) for g in notices)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(notices)} notices covering {crates} crates")


if __name__ == "__main__":
    main()
